# Generated by Django 4.0.4 on 2022-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
