# Generated by Django 4.0.4 on 2022-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
