# Generated by Django 4.0.4 on 2022-05-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_country_alter_user_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
