# Generated by Django 4.0.4 on 2022-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='exp_date',
            field=models.DateField(max_length=255),
        ),
    ]
