# Generated by Django 4.0.4 on 2022-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_paymentinfo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='cvc',
            field=models.FloatField(null=True),
        ),
    ]
