# Generated by Django 4.0.4 on 2022-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_paymentinfo_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
