# Generated by Django 4.0.4 on 2022-05-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemoffer',
            old_name='price',
            new_name='item_price',
        ),
    ]
