# Generated by Django 4.0.4 on 2022-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_price_itemoffer_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
