# Generated by Django 4.0.4 on 2022-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
