# Generated by Django 4.0.4 on 2022-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
