# Generated by Django 4.0.4 on 2022-05-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_type_notification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='item_bid',
        ),
    ]
